import {
  Search,
  User,
  Users,
  House,
  Plus,
  Pencil,
  Trash2,
  Eye,
  EyeOff,
  Menu,
  Bell,
  Settings,
  Building2,
  Calendar,
  Filter,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  ArrowLeft,
  ArrowRight,
  CircleCheck,
  X,
  Inbox,
  Mail,
  MoreHorizontal,
  LoaderCircle,
  TriangleAlert,
  Info,
  CircleX
} from 'lucide-angular';

export const LV_ICONS = {
  home: House,
  user: User,
  users: Users,
  plus: Plus,
  search: Search,
  edit: Pencil,
  delete: Trash2,
  eye: Eye,
  eyeOff: EyeOff,
  menu: Menu,
  bell: Bell,
  settings: Settings,
  company: Building2,
  calendar: Calendar,
  filter: Filter,
  check: CircleCheck,
  close: X,
  x: X,
  chevronDown: ChevronDown,
  'chevron-down': ChevronDown,
  chevronLeft: ChevronLeft,
  'chevron-left': ChevronLeft,
  chevronRight: ChevronRight,
  'chevron-right': ChevronRight,
  chevronUp: ChevronUp,
  'chevron-up': ChevronUp,
  chevronUpDown: ChevronsUpDown,
  'chevron-up-down': ChevronsUpDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  inbox: Inbox,
  mail: Mail,
  moreHorizontal: MoreHorizontal,
  'more-horizontal': MoreHorizontal,
  spinner: LoaderCircle,
  warning: TriangleAlert,
  info: Info,
  errorCircle: CircleX
} as const;

export type IconKeys = keyof typeof LV_ICONS;
export type IconComponent = typeof LV_ICONS[IconKeys];